--DROP TABLE UNICA_TEMP.XMP_AUDIENCE
CREATE MULTISET TABLE UNICA_TEMP.XMP_AUDIENCE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      AUD_ID INTEGER NOT NULL,
      AUD_NAME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	SITE_ID INTEGER NOT NULL,
	PRIORITY INTEGER NOT NULL,
	CNTRL_GRP INTEGER NOT NULL,
	CNTRL_HASH  VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	CNTRL_MONTHLY VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( AUD_ID ,START_DATE )
	)	
UNIQUE PRIMARY INDEX ( AUD_ID ,END_DATE )
UNIQUE INDEX ( AUD_NAME ,END_DATE )
INDEX (SITE_ID);
​
--DROP TABLE UNICA_TEMP.XMP_SEGMENT
CREATE MULTISET TABLE UNICA_TEMP.XMP_SEGMENT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      AUD_ID INTEGER NOT NULL,
      SEGM_ID INTEGER NOT NULL,
	SEGM_ABR VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	SEGM_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	PRIORITY INTEGER NOT NULL,
	CNTRL_GRP INTEGER NOT NULL,
	CNTRL_HASH  VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	CNTRL_MONTHLY VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( SEGM_ID ,START_DATE )
	)
UNIQUE PRIMARY INDEX ( SEGM_ID ,START_DATE )
INDEX ( AUD_ID )
INDEX ( SEGM_ID )
UNIQUE INDEX ( AUD_ID ,SEGM_NAME ,END_DATE );
​
​
--DROP TABLE UNICA_TEMP.XMP_USER_AUDIENCE_DAILY_STG
CREATE MULTISET TABLE UNICA_TEMP.XMP_USER_AUDIENCE_DAILY_STG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
	AUD_ID INTEGER NOT NULL,
	SEGM_ID INTEGER NOT NULL,
      USER_SITE_ID DECIMAL(4,0) NOT NULL,
      EXCLUDE_REASON_CD SMALLINT)
UNIQUE PRIMARY INDEX ( PRIMARY_USER_ID ,SEGM_ID,AUD_ID);
​
--DROP TABLE UNICA_TEMP.XMP_USER_AUDIENCE_DAILY
CREATE MULTISET TABLE UNICA_TEMP.XMP_USER_AUDIENCE_DAILY ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
	AUD_ID INTEGER NOT NULL,
	SEGM_ID INTEGER NOT NULL,
      USER_SITE_ID DECIMAL(4,0) NOT NULL,
      EXCLUDE_REASON_CD SMALLINT)
UNIQUE PRIMARY INDEX ( PRIMARY_USER_ID,SEGM_ID,AUD_ID);
​
--DROP TABLE UNICA_TEMP.XMP_MESSAGE
CREATE MULTISET TABLE UNICA_TEMP.XMP_MESSAGE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      MSG_ID INTEGER NOT NULL,
      MSG_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	PRIORITY INTEGER,
	FREQUENCY INTEGER NOT NULL,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( MSG_ID ,START_DATE )
	)
UNIQUE PRIMARY INDEX ( MSG_ID ,START_DATE )
INDEX ( MSG_ID )
UNIQUE INDEX ( MSG_NAME ,END_DATE );
​
​
--DROP TABLE UNICA_TEMP.XMP_MESSAGE_PLACEMENT
CREATE MULTISET TABLE UNICA_TEMP.XMP_MESSAGE_PLACEMENT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      MSG_ID INTEGER NOT NULL,
	HERO_MESSAGE_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	MESSAGE2_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	MESSAGE3_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	MESSAGE4_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( MSG_ID ,START_DATE )
	)
UNIQUE PRIMARY INDEX ( MSG_ID ,START_DATE )
INDEX ( MSG_ID )
UNIQUE INDEX ( MSG_ID ,END_DATE );
​
​
--DROP TABLE UNICA_TEMP.XMP_MESSAGE_CHANNEL
CREATE MULTISET TABLE UNICA_TEMP.XMP_MESSAGE_CHANNEL ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      MSG_ID INTEGER NOT NULL,
	EM_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	MC_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	OM_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	PN_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( MSG_ID ,START_DATE )
	)
UNIQUE PRIMARY INDEX ( MSG_ID ,START_DATE )
INDEX ( MSG_ID )
UNIQUE INDEX ( MSG_ID ,END_DATE );
​
​
--DROP TABLE UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE
CREATE MULTISET TABLE UNICA_TEMP.XMP_MAP_SEGMENT_MESSAGE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SEGM_ID INTEGER NOT NULL,
	MSG_ID INTEGER NOT NULL,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( MSG_ID ,SEGM_ID,START_DATE )
	)
UNIQUE PRIMARY INDEX ( SEGM_ID,MSG_ID ,START_DATE )
INDEX ( MSG_ID,END_DATE)
INDEX ( SEGM_ID ,END_DATE );
​
--DROP TABLE UNICA_TEMP.XMP_MESSAGE_EXCL_GRP
CREATE MULTISET TABLE UNICA_TEMP.XMP_MESSAGE_EXCL_GRP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      EXCL_GRP_ID INTEGER NOT NULL,
	EXCL_GRP_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	MSG_ID INTEGER NOT NULL,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( EXCL_GRP_ID ,MSG_ID,START_DATE )
	)
UNIQUE PRIMARY INDEX ( EXCL_GRP_ID,MSG_ID ,START_DATE )
INDEX ( EXCL_GRP_ID,END_DATE)
INDEX ( MSG_ID ,END_DATE );
​
​
--DROP TABLE UNICA_TEMP.XMP_MESSAGE_DEPENDENCY
CREATE MULTISET TABLE UNICA_TEMP.XMP_MESSAGE_DEPENDENCY ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      MSG_ID_HERO INTEGER NOT NULL,
	MSG_ID INTEGER NOT NULL,
	PLACEMENT INTEGER NOT NULL,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( MSG_ID_HERO ,MSG_ID,START_DATE )
	)
UNIQUE PRIMARY INDEX ( MSG_ID_HERO ,MSG_ID,START_DATE )
INDEX ( MSG_ID_HERO,END_DATE)
INDEX ( MSG_ID ,END_DATE );
​
​
--DROP TABLE UNICA_TEMP.XMP_USER_MESSAGE_DAILY_STG
CREATE MULTISET TABLE UNICA_TEMP.XMP_USER_MESSAGE_DAILY_STG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
	AUD_ID  INTEGER NOT NULL,
	SEGM_ID  INTEGER NOT NULL,
	MSG_ID INTEGER NOT NULL,
	JOURNEY_ID INTEGER,
	SEQUENCE INTEGER,
	PRIORITY INTEGER,
	EXCL_GRP_ID INTEGER,
	EM_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	MC_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	OM_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	PN_CHANNEL VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	HERO_MESSAGE_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	MESSAGE2_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	MESSAGE3_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	MESSAGE4_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	EXCLUDE_REASON_CD SMALLINT,
	DATA_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL
      )
UNIQUE PRIMARY INDEX (PRIMARY_USER_ID ,AUD_ID,SEGM_ID,MSG_ID);
​
​
--DROP TABLE UNICA_TEMP.XMP_JOURNEY
CREATE MULTISET TABLE UNICA_TEMP.XMP_JOURNEY ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
 	JOURNEY_ID INTEGER NOT NULL,
      JOURNEY_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	FREQUENCY INTEGER,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY ( JOURNEY_ID ,START_DATE )
	)
UNIQUE PRIMARY INDEX (JOURNEY_ID ,START_DATE)
INDEX (JOURNEY_ID)
;
​
--DROP TABLE UNICA_TEMP.XMP_MAP_JOURNEY_MESSAGE
CREATE MULTISET TABLE UNICA_TEMP.XMP_MAP_JOURNEY_MESSAGE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      JOURNEY_ID INTEGER NOT NULL,
	MSG_ID INTEGER NOT NULL,
	SEQUENCE INTEGER NOT NULL,
	START_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE ,
      END_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL DEFAULT DATE '2099-12-31',
	PRIMARY KEY (JOURNEY_ID,MSG_ID,START_DATE )
	)
UNIQUE PRIMARY INDEX ( JOURNEY_ID,MSG_ID ,START_DATE )
INDEX (JOURNEY_ID,END_DATE)
INDEX (MSG_ID,END_DATE )
;
​
-- DROP TABLE UNICA_TEMP.XMP_TARGETING_DAILY_EM_STG
CREATE MULTISET TABLE UNICA_TEMP.XMP_TARGETING_DAILY_EM_STG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
	AUD_ID  INTEGER NOT NULL,
	SEGM_ID  INTEGER NOT NULL,
	JOURNEY_ID INTEGER,
	SEQUENCE INTEGER,
	HERO_MESSAGE INTEGER,
	MESSAGE2 INTEGER,
	MESSAGE3 INTEGER,
	MESSAGE4 INTEGER,
	EXCLUDE_REASON_CD SMALLINT,
	DATA_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL
      )
UNIQUE PRIMARY INDEX (PRIMARY_USER_ID);
​
​
-- DROP TABLE UNICA_TEMP.XMP_TARGETING_DAILY_EM
CREATE MULTISET TABLE UNICA_TEMP.XMP_TARGETING_DAILY_EM, NO FALLBACK,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
	AUD_ID  INTEGER NOT NULL,
	AUD_NAME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	SEGM_ID  INTEGER NOT NULL,
	SEGM_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	JOURNEY_ID INTEGER,
	SEQUENCE INTEGER,
	HERO_MESSAGE INTEGER,
	MESSAGE2 INTEGER,
	MESSAGE3 INTEGER,
	MESSAGE4 INTEGER,
	TC VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	DATA_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL
      )
UNIQUE PRIMARY INDEX (PRIMARY_USER_ID);
​
​
-- DROP TABLE UNICA_TEMP.XMP_TARGETING_ARCHIVE
CREATE MULTISET TABLE UNICA_TEMP.XMP_TARGETING_ARCHIVE, NO FALLBACK,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
	AUD_ID  INTEGER NOT NULL,
	AUD_NAME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	SEGM_ID  INTEGER NOT NULL,
	SEGM_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	JOURNEY_ID INTEGER NOT NULL,
	SEQUENCE INTEGER,
	HERO_MESSAGE INTEGER NOT NULL,
	MESSAGE2 INTEGER NOT NULL,
	MESSAGE3 INTEGER NOT NULL,
	MESSAGE4 INTEGER NOT NULL,
	TC VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	DATA_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL,
	EMAIL_SENT_YN VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
	EMAIL_SENT_DATE DATE FORMAT 'YYYY-MM-DD' 
      )
UNIQUE PRIMARY INDEX (PRIMARY_USER_ID,DATA_DATE);
​
-- DROP TABLE UNICA_TEMP.XMP_ADOBE_SNAP
CREATE MULTISET TABLE UNICA_TEMP.XMP_ADOBE_SNAP, NO FALLBACK,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ENCRYPTED_USER_ID DECIMAL(18,0) NOT NULL,
      USER_ID DECIMAL(18,0) NOT NULL,
	SEGMENT VARCHAR(256) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	TC VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	AUD_ID  INTEGER NOT NULL,
	SEGM_ID  INTEGER NOT NULL,
	JOURNEY_ID INTEGER NOT NULL,
	SEQUENCE INTEGER,
	HERO_MODULE INTEGER NOT NULL,
	MODULE2 INTEGER NOT NULL,
	MODULE3 INTEGER NOT NULL,
	MODULE4 INTEGER NOT NULL,
	DATA_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL,
	RUN_DT DATE FORMAT 'YYYY-MM-DD' NOT NULL
	)
UNIQUE PRIMARY INDEX (ENCRYPTED_USER_ID,DATA_DATE);
​
​
-- DROP TABLE UNICA_TEMP.XMP_TARGETING_ARCHIVE_WF
CREATE MULTISET TABLE UNICA_TEMP.XMP_TARGETING_ARCHIVE_WF, NO FALLBACK,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PRIMARY_USER_ID DECIMAL(18,0) NOT NULL,
      DEMO_USER_ID DECIMAL(18,0) NOT NULL,    
	AUD_ID  INTEGER NOT NULL,
	SEGM_ID  INTEGER NOT NULL,
	JOURNEY_ID INTEGER NOT NULL,
	SEQUENCE INTEGER,
	HERO_MESSAGE INTEGER NOT NULL,
	MESSAGE2 INTEGER NOT NULL,
	MESSAGE3 INTEGER NOT NULL,
	MESSAGE4 INTEGER NOT NULL,
	EXCLUDE_REASON_CD SMALLINT,
	DATA_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL
	)
PRIMARY INDEX (PRIMARY_USER_ID,DATA_DATE);